language: android
jdk: oraclejdk8
env:
    global:
        - ANDROID_API_LEVEL=28
        - ANDROID_BUILD_TOOLS_VERSION=28.0.3
android:
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
    components:
        - tools
        - platform-tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL
        - extra-google-m2repository
        - extra-android-m2repository
install: false
before_script:
    - mkdir -p "$ANDROID_HOME/licenses"
    - cp ./.google-licenses/* "$ANDROID_HOME/licenses/"
script:
    - ./gradlew build check
